package catalog

import (
	"time"

	"github.com/syslog-platform/logger/internal/models"
)

// Rules returns the complete 72-rule detection catalog across 12 distinct categories.
func Rules() []models.SIEMRule {
	now := time.Now().UTC()
	return []models.SIEMRule{
		// =========================================================================
		// 1. Authentication and account access (AUTH-001–006)
		// =========================================================================
		{
			ID:               "AUTH-001",
			Name:             "Password spraying across accounts",
			Description:      "Detects multiple failed login attempts across different accounts from a single source IP within a short window",
			Severity:         "MEDIUM",
			RiskScore:        65,
			Category:         "authentication",
			Priority:         "P1",
			SourceRef:        "Microsoft Sentinel password-spray template",
			Threshold:        5,
			TimeframeSeconds: 1200, // 20 minutes
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1110.003",
			IsEnabled:        true,
			MatchCategory:    "authentication",
			MatchAction:      "login-failed",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "AUTH-002",
			Name:             "SSH password guessing",
			Description:      "Detects repeated SSH authentication failures targeting valid or invalid users on a specific host",
			Severity:         "MEDIUM",
			RiskScore:        60,
			Category:         "authentication",
			Priority:         "P1",
			SourceRef:        "Microsoft Sentinel SSH template",
			Threshold:        10,
			TimeframeSeconds: 300, // 5 minutes
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1110.001",
			IsEnabled:        true,
			MatchCategory:    "authentication",
			MatchAction:      "ssh-login-failed",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "AUTH-003",
			Name:             "Successful login after failures",
			Description:      "Flags a successful authentication immediately preceded by multiple consecutive failures for the same account",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "authentication",
			Priority:         "P1",
			SourceRef:        "Google YARA-L authentication example",
			Threshold:        5,
			TimeframeSeconds: 600, // 10 minutes
			GroupBy:          []string{"username"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1078",
			IsEnabled:        true,
			MatchCategory:    "authentication",
			MatchAction:      "login-success-after-failure",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "AUTH-004",
			Name:             "Distributed password spraying",
			Description:      "Detects an unusual surge in source IP diversity and distinct failed accounts across an application service",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "authentication",
			Priority:         "P2",
			SourceRef:        "Splunk — Detect Distributed Password Spray Attempts",
			Threshold:        10,
			TimeframeSeconds: 1800, // 30 minutes
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1110.003",
			IsEnabled:        true,
			MatchCategory:    "authentication",
			MatchAction:      "password-spray-distributed",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "AUTH-005",
			Name:             "Repeated denied MFA requests",
			Description:      "Detects repeated MFA push challenge denials for a single user account indicating potential MFA fatigue / push bombing",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "authentication",
			Priority:         "P1",
			SourceRef:        "Splunk — Azure AD Multiple Denied MFA Requests For User",
			Threshold:        10,
			TimeframeSeconds: 600, // 10 minutes
			GroupBy:          []string{"username"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1621",
			IsEnabled:        true,
			MatchCategory:    "authentication",
			MatchAction:      "mfa-denied",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "AUTH-006",
			Name:             "Cloud console login from a new country",
			Description:      "Identifies successful administrative cloud console logon originating from a geographic location previously unobserved",
			Severity:         "MEDIUM",
			RiskScore:        65,
			Category:         "authentication",
			Priority:         "P2",
			SourceRef:        "Splunk — Detect AWS Console Login by User from New Country",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Initial Access",
			MitreTechnique:   "T1078.004",
			IsEnabled:        true,
			MatchCategory:    "authentication",
			MatchAction:      "console-login-new-country",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 2. Privilege escalation and Active Directory (PRIV-001–006)
		// =========================================================================
		{
			ID:               "PRIV-001",
			Name:             "New local administrator account",
			Description:      "Detects creation of a new local user account followed immediately by addition to the local Administrators group",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "privilege",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect New Local Admin account",
			Threshold:        1,
			TimeframeSeconds: 1800, // 30 minutes
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1136.001",
			IsEnabled:        true,
			MatchCategory:    "privilege",
			MatchAction:      "local-admin-created",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PRIV-002",
			Name:             "Member added to a privileged AD group",
			Description:      "Alerts when an account is added to a sensitive directory group such as Enterprise Admins or Domain Admins",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "privilege",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows AD Privileged Group Modification",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1098",
			IsEnabled:        true,
			MatchCategory:    "privilege",
			MatchAction:      "ad-privileged-group-add",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PRIV-003",
			Name:             "Directory replication by an unexpected account",
			Description:      "Detects non-machine user accounts invoking DS-Replication-Get-Changes (potential DCSync attack)",
			Severity:         "HIGH",
			RiskScore:        95,
			Category:         "privilege",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows AD Replication Request Initiated by User Account",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1003.006",
			IsEnabled:        true,
			MatchCategory:    "privilege",
			MatchAction:      "ad-dcsync-replication",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PRIV-004",
			Name:             "Suspicious Kerberos service-ticket requests",
			Description:      "Identifies RC4 encryption service-ticket requests across multiple SPNs characteristic of Kerberoasting",
			Severity:         "MEDIUM",
			RiskScore:        70,
			Category:         "privilege",
			Priority:         "P2",
			SourceRef:        "Splunk — Kerberoasting spn request with RC4 encryption",
			Threshold:        5,
			TimeframeSeconds: 300,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1558.003",
			IsEnabled:        true,
			MatchCategory:    "privilege",
			MatchAction:      "kerberoasting-ticket-request",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PRIV-005",
			Name:             "Privileged SID added to SID history",
			Description:      "Detects addition of well-known privileged administrative SIDs (e.g. Enterprise Admins -519) into sIDHistory",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "privilege",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows AD Privileged Account SID History Addition",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Privilege Escalation",
			MitreTechnique:   "T1134.005",
			IsEnabled:        true,
			MatchCategory:    "privilege",
			MatchAction:      "sid-history-privileged-added",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PRIV-006",
			Name:             "Dangerous permissions added to an AD group",
			Description:      "Detects ACL modification granting WriteDacl, WriteOwner, or GenericAll control over sensitive Active Directory objects",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "privilege",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows AD Dangerous Group ACL Modification",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Privilege Escalation",
			MitreTechnique:   "T1484",
			IsEnabled:        true,
			MatchCategory:    "privilege",
			MatchAction:      "ad-dangerous-acl-modified",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 3. Switch and router administration (NETADM-001–006)
		// =========================================================================
		{
			ID:               "NETADM-001",
			Name:             "New account-to-network-device login relationship",
			Description:      "Flags administrative authentication to a core switch or router by an account never previously observed on that asset",
			Severity:         "MEDIUM",
			RiskScore:        60,
			Category:         "network_admin",
			Priority:         "P2",
			SourceRef:        "Splunk — Detect New Login Attempts to Routers",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Initial Access",
			MitreTechnique:   "T1078",
			IsEnabled:        true,
			MatchCategory:    "network_admin",
			MatchAction:      "network-device-new-login",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NETADM-002",
			Name:             "Traffic mirroring or capture enabled",
			Description:      "Detects configuration or activation of SPAN, RSPAN, ERSPAN or packet capture sessions on network switches or routers",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "network_admin",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect Traffic Mirroring",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1040",
			IsEnabled:        true,
			MatchCategory:    "network_admin",
			MatchAction:      "traffic-mirroring-enabled",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NETADM-003",
			Name:             "Unexpected software transfer involving a network device",
			Description:      "Flags TFTP, SCP, or FTP firmware/boot-image file transfers involving network devices with unapproved peers",
			Severity:         "MEDIUM",
			RiskScore:        70,
			Category:         "network_admin",
			Priority:         "P2",
			SourceRef:        "Splunk — Detect Software Download To Network Device",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1542.001",
			IsEnabled:        true,
			MatchCategory:    "network_admin",
			MatchAction:      "network-device-software-transfer",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NETADM-004",
			Name:             "DHCP response on an untrusted port",
			Description:      "Alerts when DHCP snooping detects unauthorized DHCPOFFER or DHCPACK packets from a rogue server on an untrusted edge port",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "network_admin",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect Rogue DHCP Server",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1557.001",
			IsEnabled:        true,
			MatchCategory:    "network_admin",
			MatchAction:      "dhcp-rogue-server-detected",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NETADM-005",
			Name:             "ARP inspection violation",
			Description:      "Detects Dynamic ARP Inspection (DAI) drops caused by IP-to-MAC spoofing attempts on access interfaces",
			Severity:         "MEDIUM",
			RiskScore:        65,
			Category:         "network_admin",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect ARP Poisoning",
			Threshold:        5,
			TimeframeSeconds: 300,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1557.002",
			IsEnabled:        true,
			MatchCategory:    "network_admin",
			MatchAction:      "arp-inspection-violation",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NETADM-006",
			Name:             "Port-security violation",
			Description:      "Alerts when switch port-security detects an unauthorized MAC address attempting transmission on a locked port",
			Severity:         "MEDIUM",
			RiskScore:        60,
			Category:         "network_admin",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect Port Security Violation",
			Threshold:        3,
			TimeframeSeconds: 300,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Initial Access",
			MitreTechnique:   "T1200",
			IsEnabled:        true,
			MatchCategory:    "network_admin",
			MatchAction:      "port-security-violation",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 4. Firewall, VPN and perimeter control (PERIM-001–006)
		// =========================================================================
		{
			ID:               "PERIM-001",
			Name:             "Administrative AAA policy weakened",
			Description:      "Detects firewall configuration commands modifying administrative authentication, disabling lockouts, or falling back to local credentials",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "perimeter",
			Priority:         "P1",
			SourceRef:        "Splunk — Cisco ASA - AAA Policy Tampering",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.001",
			IsEnabled:        true,
			MatchCategory:    "perimeter",
			MatchAction:      "aaa-policy-tampering",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PERIM-002",
			Name:             "Firewall configuration or files copied off-device",
			Description:      "Identifies extraction of firewall startup-config, credentials, or packet captures to external unapproved destinations",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "perimeter",
			Priority:         "P1",
			SourceRef:        "Splunk — Cisco ASA - Device File Copy to Remote Location",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Collection",
			MitreTechnique:   "T1005",
			IsEnabled:        true,
			MatchCategory:    "perimeter",
			MatchAction:      "firewall-config-exported",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PERIM-003",
			Name:             "Unexpected remote-administration software traffic",
			Description:      "Flags perimeter firewall connections matching unapproved remote desktop or support tools (AnyDesk, TeamViewer, RustDesk)",
			Severity:         "MEDIUM",
			RiskScore:        70,
			Category:         "perimeter",
			Priority:         "P2",
			SourceRef:        "Splunk — Cisco Secure Firewall - Remote Access Software Usage Traffic",
			Threshold:        3,
			TimeframeSeconds: 300,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Command and Control",
			MitreTechnique:   "T1219",
			IsEnabled:        true,
			MatchCategory:    "perimeter",
			MatchAction:      "remote-access-software-traffic",
			MatchOutcome:     "allowed",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PERIM-004",
			Name:             "High-priority intrusion event",
			Description:      "Alerts when perimeter IPS/IDS classifies a high-impact exploit or remote code execution probe",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "perimeter",
			Priority:         "P1",
			SourceRef:        "Splunk — Cisco Secure Firewall - High Priority Intrusion Classification",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Initial Access",
			MitreTechnique:   "T1190",
			IsEnabled:        true,
			MatchCategory:    "threat",
			MatchAction:      "intrusion-high-priority",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PERIM-005",
			Name:             "Overly permissive firewall policy introduced",
			Description:      "Detects introduction of an any-any permit rule or modification that bypasses deep inspection on an edge security gateway",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "perimeter",
			Priority:         "P1",
			SourceRef:        "Original Logger control",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.004",
			IsEnabled:        true,
			MatchCategory:    "perimeter",
			MatchAction:      "firewall-permissive-rule-added",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "PERIM-006",
			Name:             "Risky identity correlated with perimeter activity",
			Description:      "Correlates external VPN / firewall sessions with accounts tagged with high identity risk or impossible travel",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "perimeter",
			Priority:         "P2",
			SourceRef:        "Microsoft Sentinel risky-user network correlation",
			Threshold:        1,
			TimeframeSeconds: 1800,
			GroupBy:          []string{"username"},
			MitreTactic:      "Initial Access",
			MitreTechnique:   "T1078",
			IsEnabled:        true,
			MatchCategory:    "perimeter",
			MatchAction:      "risky-user-perimeter-activity",
			MatchOutcome:     "allowed",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 5. Network reconnaissance and suspicious traffic (NET-001–006)
		// =========================================================================
		{
			ID:               "NET-001",
			Name:             "Horizontal scanning across hosts",
			Description:      "Detects a single internal source attempting connections across a large number of distinct destination hosts",
			Severity:         "MEDIUM",
			RiskScore:        60,
			Category:         "network",
			Priority:         "P2",
			SourceRef:        "Splunk — Internal Horizontal Port Scan",
			Threshold:        50,
			TimeframeSeconds: 300,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Discovery",
			MitreTechnique:   "T1046",
			IsEnabled:        true,
			MatchCategory:    "network",
			MatchAction:      "connection-denied",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NET-002",
			Name:             "Vertical scanning across ports",
			Description:      "Flags a single host rapidly scanning dozens of distinct destination ports on a single internal target",
			Severity:         "MEDIUM",
			RiskScore:        60,
			Category:         "network",
			Priority:         "P2",
			SourceRef:        "Splunk — Internal Vertical Port Scan",
			Threshold:        50,
			TimeframeSeconds: 300,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Discovery",
			MitreTechnique:   "T1046",
			IsEnabled:        true,
			MatchCategory:    "network",
			MatchAction:      "vertical-port-scan",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NET-003",
			Name:             "SMB connection to an external host",
			Description:      "Alerts on outbound SMB (TCP port 445) connections from inside assets destined to public internet addresses",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "network",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect Outbound SMB Traffic",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Lateral Movement",
			MitreTechnique:   "T1021.002",
			IsEnabled:        true,
			MatchCategory:    "network",
			MatchAction:      "outbound-smb-traffic",
			MatchOutcome:     "allowed",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NET-004",
			Name:             "LDAP connection to an external host",
			Description:      "Detects outbound LDAP/LDAPS traffic to external unapproved destinations, indicating potential credential relay or reconnaissance",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "network",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect Outbound LDAP Traffic",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Discovery",
			MitreTechnique:   "T1087.002",
			IsEnabled:        true,
			MatchCategory:    "network",
			MatchAction:      "outbound-ldap-traffic",
			MatchOutcome:     "allowed",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NET-005",
			Name:             "Unusual DNS query lengths",
			Description:      "Detects anomalously long DNS queries characteristic of DNS tunneling or data exfiltration via TXT/A queries",
			Severity:         "MEDIUM",
			RiskScore:        65,
			Category:         "network",
			Priority:         "P2",
			SourceRef:        "Splunk — DNS Query Length With High Standard Deviation",
			Threshold:        10,
			TimeframeSeconds: 900,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Command and Control",
			MitreTechnique:   "T1071.004",
			IsEnabled:        true,
			MatchCategory:    "network",
			MatchAction:      "dns-query-length-anomaly",
			MatchOutcome:     "allowed",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "NET-006",
			Name:             "Large outbound transfer to an unusual destination",
			Description:      "Flags large volume outbound transfers (>=100MB) from an internal host to an untrusted external endpoint exceeding baseline",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "network",
			Priority:         "P2",
			SourceRef:        "Splunk — Cisco Secure Firewall - Potential Data Exfiltration",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Exfiltration",
			MitreTechnique:   "T1048.003",
			IsEnabled:        true,
			MatchCategory:    "network",
			MatchAction:      "outbound-large-transfer",
			MatchOutcome:     "allowed",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 6. Windows execution and persistence (WIN-001–006)
		// =========================================================================
		{
			ID:               "WIN-001",
			Name:             "Suspicious LSASS memory access",
			Description:      "Detects unauthorized processes requesting PROCESS_VM_READ access to lsass.exe for credential dumping",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "windows",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect Credential Dumping through LSASS access",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1003.001",
			IsEnabled:        true,
			MatchCategory:    "windows",
			MatchAction:      "lsass-memory-access",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "WIN-002",
			Name:             "Office application starts an unusual child",
			Description:      "Alerts when Word, Excel, or PowerPoint spawns cmd.exe, powershell.exe, wscript.exe, or mshta.exe",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "windows",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows Office Product Spawned Uncommon Process",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Execution",
			MitreTechnique:   "T1204.002",
			IsEnabled:        true,
			MatchCategory:    "windows",
			MatchAction:      "office-spawned-shell",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "WIN-003",
			Name:             "Suspicious PowerShell script content",
			Description:      "Identifies execution of known offensive PowerShell payloads or AMSI bypass keywords in script block logging (Event ID 4104)",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "windows",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows PowerShell Script Block With Malicious String",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Execution",
			MitreTechnique:   "T1059.001",
			IsEnabled:        true,
			MatchCategory:    "windows",
			MatchAction:      "powershell-malicious-string",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "WIN-004",
			Name:             "Scheduled task with a suspicious action",
			Description:      "Detects scheduled task creation or modification executing binaries out of temporary or user-writable locations",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "windows",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows Scheduled Task with Suspicious Command",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1053.005",
			IsEnabled:        true,
			MatchCategory:    "windows",
			MatchAction:      "scheduled-task-suspicious",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "WIN-005",
			Name:             "New service from an unusual executable path",
			Description:      "Alerts when a Windows service (Event ID 7045) is installed pointing to AppData, Temp, or remote UNC paths",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "windows",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows Service Created with Suspicious Service Path",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1543.003",
			IsEnabled:        true,
			MatchCategory:    "windows",
			MatchAction:      "service-created-unusual-path",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "WIN-006",
			Name:             "Permanent WMI execution subscription",
			Description:      "Identifies creation of CommandLineEventConsumer or ActiveScriptEventConsumer WMI subscriptions for persistence",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "windows",
			Priority:         "P1",
			SourceRef:        "Splunk — WMI Permanent Event Subscription",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1546.003",
			IsEnabled:        true,
			MatchCategory:    "windows",
			MatchAction:      "wmi-event-subscription-created",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 7. Linux privilege and persistence (LIN-001–006)
		// =========================================================================
		{
			ID:               "LIN-001",
			Name:             "Passwordless sudo privilege added",
			Description:      "Detects additions of NOPASSWD directives to /etc/sudoers or /etc/sudoers.d/ configuration files",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "linux",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux Auditd Nopasswd Entry In Sudoers File",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Privilege Escalation",
			MitreTechnique:   "T1548.003",
			IsEnabled:        true,
			MatchCategory:    "linux",
			MatchAction:      "sudoers-nopasswd-added",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "LIN-002",
			Name:             "SSH authorized key changed",
			Description:      "Alerts on unauthorized modification or insertion of public keys into root or administrative authorized_keys files",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "linux",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux SSH Authorized Keys Modification",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1098.004",
			IsEnabled:        true,
			MatchCategory:    "linux",
			MatchAction:      "ssh-authorized-keys-modified",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "LIN-003",
			Name:             "Unexpected cron persistence",
			Description:      "Detects appending of scheduled jobs in cron tables downloading remote scripts or executing reverse shells",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "linux",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux Possible Append Cronjob Entry on Existing Cronjob File",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1053.003",
			IsEnabled:        true,
			MatchCategory:    "linux",
			MatchAction:      "cronjob-entry-appended",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "LIN-004",
			Name:             "New systemd service unit",
			Description:      "Flags creation of new systemd service unit files executing out of writable or non-standard directory locations",
			Severity:         "MEDIUM",
			RiskScore:        70,
			Category:         "linux",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux Service File Created In Systemd Directory",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1543.002",
			IsEnabled:        true,
			MatchCategory:    "linux",
			MatchAction:      "systemd-unit-created",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "LIN-005",
			Name:             "Unexpected access to credential files",
			Description:      "Alerts on unauthorized read or copy access to /etc/shadow, /etc/gshadow, or master passwd databases",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "linux",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux Possible Access To Credential Files",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1003.008",
			IsEnabled:        true,
			MatchCategory:    "linux",
			MatchAction:      "credential-file-accessed",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "LIN-006",
			Name:             "Non-root account assigned UID zero",
			Description:      "Detects modification of account credentials assigning UID 0 (root superuser identity) to a non-standard username",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "linux",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux Usermod Root UID Set",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1136.001",
			IsEnabled:        true,
			MatchCategory:    "linux",
			MatchAction:      "usermod-root-uid-set",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 8. Cloud identity and control-plane changes (CLOUD-001–006)
		// =========================================================================
		{
			ID:               "CLOUD-001",
			Name:             "Cloud audit logging stopped",
			Description:      "Alerts on StopLogging API actions disabling AWS CloudTrail, GCP Audit Logs, or Azure Activity Logs",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "cloud",
			Priority:         "P1",
			SourceRef:        "Splunk — AWS Defense Evasion Stop Logging Cloudtrail",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.008",
			IsEnabled:        true,
			MatchCategory:    "cloud",
			MatchAction:      "cloudtrail-stop-logging",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "CLOUD-002",
			Name:             "Access key created for another identity",
			Description:      "Detects IAM CreateAccessKey actions performed by one principal generating credentials for a different account",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "cloud",
			Priority:         "P1",
			SourceRef:        "Splunk — AWS CreateAccessKey",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1098.001",
			IsEnabled:        true,
			MatchCategory:    "cloud",
			MatchAction:      "iam-create-access-key-other",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "CLOUD-003",
			Name:             "Object-storage access made public",
			Description:      "Flags permissions modifications removing public access blocks or granting AllUsers / AuthenticatedUsers access to S3/Blob storage",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "cloud",
			Priority:         "P1",
			SourceRef:        "Splunk — Detect New Open S3 buckets",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Collection",
			MitreTechnique:   "T1530",
			IsEnabled:        true,
			MatchCategory:    "cloud",
			MatchAction:      "s3-bucket-open-public",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "CLOUD-004",
			Name:             "Overly broad IAM policy version created",
			Description:      "Detects creation of IAM policy versions granting Action:* across Resource:* to any principal",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "cloud",
			Priority:         "P1",
			SourceRef:        "Splunk — AWS Create Policy Version to allow all resources",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Privilege Escalation",
			MitreTechnique:   "T1484",
			IsEnabled:        true,
			MatchCategory:    "cloud",
			MatchAction:      "iam-policy-allow-all-resources",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "CLOUD-005",
			Name:             "New application or service-principal credential",
			Description:      "Alerts when new certificates or client secrets are added to sensitive Entra ID / AWS service principals",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "cloud",
			Priority:         "P1",
			SourceRef:        "Splunk — Azure AD Service Principal New Client Credentials",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1098.001",
			IsEnabled:        true,
			MatchCategory:    "cloud",
			MatchAction:      "azure-ad-service-principal-credential-added",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "CLOUD-006",
			Name:             "Risky OAuth application consent",
			Description:      "Identifies user or administrator grants of broad Mail.ReadWrite, Files.ReadWrite, or Directory.AccessAsUser scopes to unverified apps",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "cloud",
			Priority:         "P2",
			SourceRef:        "Splunk — Azure AD OAuth Application Consent Granted By User",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Credential Access",
			MitreTechnique:   "T1528",
			IsEnabled:        true,
			MatchCategory:    "cloud",
			MatchAction:      "oauth-consent-granted-risky",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 9. Email, collaboration and web applications (MAILWEB-001–006)
		// =========================================================================
		{
			ID:               "MAILWEB-001",
			Name:             "Mailbox forwarding enabled externally",
			Description:      "Detects mailbox configuration changes establishing automated forwarding or redirect rules to outside external domains",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "mail_web",
			Priority:         "P1",
			SourceRef:        "Splunk — O365 Mailbox Email Forwarding Enabled",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Collection",
			MitreTechnique:   "T1114.003",
			IsEnabled:        true,
			MatchCategory:    "mail_web",
			MatchAction:      "mailbox-forwarding-enabled",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "MAILWEB-002",
			Name:             "Inbox rule hides or deletes security-related mail",
			Description:      "Alerts when an inbox rule is created to automatically move or delete emails referencing security alerts, invoices, or wire transfers",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "mail_web",
			Priority:         "P1",
			SourceRef:        "Splunk — O365 Email New Inbox Rule Created",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1564.008",
			IsEnabled:        true,
			MatchCategory:    "mail_web",
			MatchAction:      "inbox-rule-created-suspicious",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "MAILWEB-003",
			Name:             "Unusual external email attachment volume",
			Description:      "Detects a high volume burst of external emails carrying file attachments sent by an individual mailbox within an hour",
			Severity:         "HIGH",
			RiskScore:        80,
			Category:         "mail_web",
			Priority:         "P2",
			SourceRef:        "Splunk — O365 Email Send Attachments Excessive Volume",
			Threshold:        20,
			TimeframeSeconds: 3600,
			GroupBy:          []string{"username"},
			MitreTactic:      "Exfiltration",
			MitreTechnique:   "T1048.003",
			IsEnabled:        true,
			MatchCategory:    "mail_web",
			MatchAction:      "excessive-attachment-volume",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "MAILWEB-004",
			Name:             "Suspicious process execution on a web server",
			Description:      "Alerts when a web worker process (w3wp.exe, httpd, nginx) launches shells, downloaders, or discovery tools",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "mail_web",
			Priority:         "P1",
			SourceRef:        "Splunk — Web Servers Executing Suspicious Processes",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Persistence",
			MitreTechnique:   "T1505.003",
			IsEnabled:        true,
			MatchCategory:    "mail_web",
			MatchAction:      "webserver-spawned-shell",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "MAILWEB-005",
			Name:             "Possible SQL injection in HTTP input",
			Description:      "Detects SQL syntax keywords in abnormally long or structured HTTP request parameters (WAF / Web audit logs)",
			Severity:         "MEDIUM",
			RiskScore:        70,
			Category:         "mail_web",
			Priority:         "P2",
			SourceRef:        "Splunk — SQL Injection with Long URLs",
			Threshold:        3,
			TimeframeSeconds: 300,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Initial Access",
			MitreTechnique:   "T1190",
			IsEnabled:        true,
			MatchCategory:    "mail_web",
			MatchAction:      "sql-injection-attempt",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "MAILWEB-006",
			Name:             "Malware detected in a collaboration file",
			Description:      "Alerts when an antimalware scanner detects malicious code inside files uploaded to SharePoint, OneDrive, or Google Workspace",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "mail_web",
			Priority:         "P1",
			SourceRef:        "Splunk — O365 SharePoint Malware Detection",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Execution",
			MitreTechnique:   "T1204.002",
			IsEnabled:        true,
			MatchCategory:    "mail_web",
			MatchAction:      "sharepoint-malware-detected",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 10. Data theft, ransomware and recovery interference (DATA-001–006)
		// =========================================================================
		{
			ID:               "DATA-001",
			Name:             "Shadow-copy deletion attempt",
			Description:      "Detects vssadmin, wmic, or powershell commands attempting to delete volume shadow copies to prevent file recovery",
			Severity:         "HIGH",
			RiskScore:        95,
			Category:         "data",
			Priority:         "P1",
			SourceRef:        "Splunk — Deleting Shadow Copies",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Impact",
			MitreTechnique:   "T1490",
			IsEnabled:        true,
			MatchCategory:    "data",
			MatchAction:      "shadow-copy-deleted",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DATA-002",
			Name:             "System backup or catalog deletion",
			Description:      "Identifies execution of wbadmin delete catalog or backup engine commands destroying recovery points",
			Severity:         "HIGH",
			RiskScore:        95,
			Category:         "data",
			Priority:         "P1",
			SourceRef:        "Splunk — WBAdmin Delete System Backups",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Impact",
			MitreTechnique:   "T1490",
			IsEnabled:        true,
			MatchCategory:    "data",
			MatchAction:      "system-backup-deleted",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DATA-003",
			Name:             "Burst of suspicious file-extension changes",
			Description:      "Detects rapid renaming of multiple files across directories to known ransomware extensions (.locked, .crypted, etc.)",
			Severity:         "HIGH",
			RiskScore:        95,
			Category:         "data",
			Priority:         "P1",
			SourceRef:        "Splunk — Common Ransomware Extensions",
			Threshold:        20,
			TimeframeSeconds: 120, // 2 minutes
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Impact",
			MitreTechnique:   "T1486",
			IsEnabled:        true,
			MatchCategory:    "data",
			MatchAction:      "ransomware-extension-burst",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DATA-004",
			Name:             "Security and backup services stopped together",
			Description:      "Alerts when critical antivirus and system backup services are terminated or disabled in rapid succession",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "data",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows Security And Backup Services Stop",
			Threshold:        2,
			TimeframeSeconds: 300,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Impact",
			MitreTechnique:   "T1489",
			IsEnabled:        true,
			MatchCategory:    "data",
			MatchAction:      "security-backup-services-stopped",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DATA-005",
			Name:             "Unapproved bulk transfer using rclone",
			Description:      "Detects rclone command-line tool execution syncing sensitive filesystem directories to unauthorized cloud remotes",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "data",
			Priority:         "P2",
			SourceRef:        "Splunk — Detect RClone Command-Line Usage",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Exfiltration",
			MitreTechnique:   "T1567.002",
			IsEnabled:        true,
			MatchCategory:    "data",
			MatchAction:      "rclone-transfer-executed",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DATA-006",
			Name:             "Unusual bulk download from collaboration storage",
			Description:      "Flags bulk mass downloads of >=100 unique documents by an account from corporate cloud collaboration drives",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "data",
			Priority:         "P2",
			SourceRef:        "Splunk — O365 Exfiltration via File Download",
			Threshold:        100,
			TimeframeSeconds: 1800,
			GroupBy:          []string{"username"},
			MitreTactic:      "Collection",
			MitreTechnique:   "T1530",
			IsEnabled:        true,
			MatchCategory:    "data",
			MatchAction:      "collaboration-bulk-file-download",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 11. Defense evasion and threat-indicator matches (DEF-001–006)
		// =========================================================================
		{
			ID:               "DEF-001",
			Name:             "Windows event logs cleared",
			Description:      "Detects intentional clearing of the Windows Security (Event ID 1102) or System (Event ID 104) log channels",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "defense_evasion",
			Priority:         "P1",
			SourceRef:        "Splunk log-clearing guidance",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1070.001",
			IsEnabled:        true,
			MatchCategory:    "defense_evasion",
			MatchAction:      "eventlog-cleared",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DEF-002",
			Name:             "Important Windows auditing removed",
			Description:      "Alerts when auditpol commands or group policy updates disable success or failure auditing for key security categories",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "defense_evasion",
			Priority:         "P1",
			SourceRef:        "Splunk — Windows Important Audit Policy Disabled",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.002",
			IsEnabled:        true,
			MatchCategory:    "defense_evasion",
			MatchAction:      "audit-policy-disabled",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DEF-003",
			Name:             "Broad Defender exclusion added",
			Description:      "Detects additions of broad folder, extension, or process exclusions to Windows Defender settings",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "defense_evasion",
			Priority:         "P1",
			SourceRef:        "Splunk — Add or Set Windows Defender Exclusion",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.001",
			IsEnabled:        true,
			MatchCategory:    "defense_evasion",
			MatchAction:      "defender-exclusion-added",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DEF-004",
			Name:             "Linux endpoint monitoring service stopped",
			Description:      "Alerts when auditd, sysmon, or endpoint telemetry services are terminated or stopped outside maintenance windows",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "defense_evasion",
			Priority:         "P1",
			SourceRef:        "Splunk — Linux Auditd Sysmon Service Stop",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.001",
			IsEnabled:        true,
			MatchCategory:    "defense_evasion",
			MatchAction:      "sysmon-service-stopped",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DEF-005",
			Name:             "Executed file matches malicious hash",
			Description:      "Identifies process execution of an executable whose SHA-256 matches an active high-confidence threat intelligence feed",
			Severity:         "HIGH",
			RiskScore:        95,
			Category:         "defense_evasion",
			Priority:         "P2",
			SourceRef:        "Google YARA-L file-indicator example",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Execution",
			MitreTechnique:   "T1204.002",
			IsEnabled:        true,
			MatchCategory:    "defense_evasion",
			MatchAction:      "malicious-hash-matched",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "DEF-006",
			Name:             "DNS request matches malicious-domain intelligence",
			Description:      "Detects resolution requests for domains attributed to active C2 servers or malware distribution infrastructure",
			Severity:         "HIGH",
			RiskScore:        90,
			Category:         "defense_evasion",
			Priority:         "P2",
			SourceRef:        "Google YARA-L domain-indicator example",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"source_ip"},
			MitreTactic:      "Command and Control",
			MitreTechnique:   "T1071.004",
			IsEnabled:        true,
			MatchCategory:    "defense_evasion",
			MatchAction:      "malicious-domain-matched",
			MatchOutcome:     "blocked",
			CreatedAt:        now,
			UpdatedAt:        now,
		},

		// =========================================================================
		// 12. Logger health, integrity and administrative controls (HEALTH-001–006)
		// =========================================================================
		{
			ID:               "HEALTH-001",
			Name:             "Critical log source becomes silent",
			Description:      "Alerts when a designated Tier-1 mission-critical syslog source stops emitting logs beyond its expected silence window",
			Severity:         "HIGH",
			RiskScore:        75,
			Category:         "health",
			Priority:         "P1",
			SourceRef:        "Original Logger operational control",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562",
			IsEnabled:        true,
			MatchCategory:    "health",
			MatchAction:      "source-silent-missed-heartbeats",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "HEALTH-002",
			Name:             "Parser or normalization failure surge",
			Description:      "Identifies a sudden surge in parsing failures (>5% of messages) indicating protocol changes, firmware updates, or malformed packets",
			Severity:         "HIGH",
			RiskScore:        75,
			Category:         "health",
			Priority:         "P1",
			SourceRef:        "Original Logger operational control",
			Threshold:        5,
			TimeframeSeconds: 600,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562",
			IsEnabled:        true,
			MatchCategory:    "health",
			MatchAction:      "parser-failure-surge",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "HEALTH-003",
			Name:             "Ingestion lag or sustained queue backlog",
			Description:      "Detects ingestion pipeline processing delays or sustained queue buffer depth exceeding operational thresholds",
			Severity:         "HIGH",
			RiskScore:        70,
			Category:         "health",
			Priority:         "P1",
			SourceRef:        "Original Logger operational control",
			Threshold:        2,
			TimeframeSeconds: 600,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Impact",
			MitreTechnique:   "T1499",
			IsEnabled:        true,
			MatchCategory:    "health",
			MatchAction:      "queue-backlog-latency-surge",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "HEALTH-004",
			Name:             "Detection execution failure or missed schedule",
			Description:      "Alerts when a detection rule or scheduled background analytics job experiences consecutive execution errors",
			Severity:         "HIGH",
			RiskScore:        75,
			Category:         "health",
			Priority:         "P1",
			SourceRef:        "Original Logger operational control",
			Threshold:        2,
			TimeframeSeconds: 600,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562",
			IsEnabled:        true,
			MatchCategory:    "health",
			MatchAction:      "detection-schedule-failure",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "HEALTH-005",
			Name:             "Unauthorized rule or exception change",
			Description:      "Detects deletion, disabling, or broad suppression exclusion modifications made to high-severity detection rules",
			Severity:         "HIGH",
			RiskScore:        85,
			Category:         "health",
			Priority:         "P1",
			SourceRef:        "Original Logger operational control",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"username"},
			MitreTactic:      "Defense Evasion",
			MitreTechnique:   "T1562.001",
			IsEnabled:        true,
			MatchCategory:    "health",
			MatchAction:      "unauthorized-rule-tampering",
			MatchOutcome:     "success",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
		{
			ID:               "HEALTH-006",
			Name:             "Evidence integrity or retention verification fails",
			Description:      "Alerts on cryptographic hash or digital signature verification failures across immutable 5651 log archives and .zd tokens",
			Severity:         "HIGH",
			RiskScore:        95,
			Category:         "health",
			Priority:         "P1",
			SourceRef:        "Original Logger integrity control",
			Threshold:        1,
			TimeframeSeconds: 60,
			GroupBy:          []string{"device_name"},
			MitreTactic:      "Impact",
			MitreTechnique:   "T1565.001",
			IsEnabled:        true,
			MatchCategory:    "health",
			MatchAction:      "evidence-integrity-mismatch",
			MatchOutcome:     "failure",
			CreatedAt:        now,
			UpdatedAt:        now,
		},
	}
}
